name: Get Daily counts
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  get_count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get count
        run: |
          set -e
          RELEASE_INFO=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/homebrew-risingwave/releases/latest)
          OSX_DOWNLOADS=$(echo $RELEASE_INFO \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | paste -sd+ - | bc)
          OSX_TAG=$(echo $RELEASE_INFO \
            | grep "tag_name" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | sed 's/"//g' )
          echo "OSX Downloads for $OSX_TAG: $OSX_DOWNLOADS"
          LINUX_INFO=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/risingwave/releases/latest)
          LINUX_DOWNLOADS=$(echo $LINUX_INFO \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | paste -sd+ - | bc)
          LINUX_TAG=$(echo $LINUX_INFO \
            | grep "tag_name" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | sed 's/"//g' )
          
          echo "Linux Downloads for $LINUX_TAG: $LINUX_DOWNLOADS"
          DATE=$(date +'%Y-%m-%d')
          echo "Date: $DATE"
          git config --global user.email "noelkwan@risingwave-labs.com"
          git config --global user.name "Noel Kwan"
          cp update_data.py update_data.tmp.py
          cp get_total_counts.py get_total_counts.tmp.py
          git fetch origin data
          git checkout data
          ./update_data.tmp.py $DATE $OSX_DOWNLOADS $LINUX_DOWNLOADS $LINUX_TAG
          ./get_total_counts.tmp.py
          git add counts.json count_versioned.json
          git commit -m "Update counts for $DATE" --allow-empty
          git push -f
          git checkout -
          echo "Done"