name: Get Daily counts
on: [push]
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  get_count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get count
        run: |
          OSX_DOWNLOADS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/homebrew-risingwave/releases/latest \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g')
          echo "OSX Downloads: $OSX_DOWNLOADS"
          LINUX_DOWNLOADS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/risingwave/releases/latest \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g')
          echo "Linux Downloads: $LINUX_DOWNLOADS"
          DATE=$(date +'%Y-%m-%d')
          echo "Date: $DATE"