name: Get Daily counts
on: [push]
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  get_count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get count
        run: |
          set -e
          OSX_DOWNLOADS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/homebrew-risingwave/releases/latest \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | paste -sd+ - | bc)
          echo "OSX Downloads: $OSX_DOWNLOADS"
          LINUX_DOWNLOADS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/risingwavelabs/risingwave/releases/latest \
            | grep "download_count" \
            | awk '{print $2}' \
            | sed 's/,//g' \
            | paste -sd+ - | bc)
          echo "Linux Downloads: $LINUX_DOWNLOADS"
          DATE=$(date +'%Y-%m-%d')
          echo "Date: $DATE"
          git clone -b data --single-branch https://"${{ secrets.GITHUB_TOKEN }}"@github.com/risingwavelabs/risingwave-download-metrics.git
          git add .
          git commit --amend --no-edit
          git push -f
          git checkout -
          echo "Done"